<div class="wrapper mt-20 mb-20">	<section class="blocks">		<h2>Users List</h2>		<!--div class="row top_btn">		<div class="btn_block">			<a href="<?php //echo SITE_URL ;?>/seller_add" class="btn">seller add</a>		</div-->		<table class='users_table'>			<thead>				<tr>					<th>id</th>					<th>Store Name</th>					<th>Email</th>					<th>Mobile</th>					<th>GST</th>					<th>Status</th>					<th>Store logo</th>					<!--<th>Edit</th>-->					<th class="no-sort">View</th>					<th>Delete</th>				</tr>			</thead>			<tbody><?php$crud = new Crud; $sql="SELECT id,name_online_store ,email,password,mobile,gstin,status,user_type,store_logo from users where user_type = 2";$result = $crud->getData($sql);                 $imageurl=IMAGE_SITE_URL.'/';						if(!empty($result)){	$i = 0;	foreach($result as $res){		$i++;		if($res['status']==0){			$status = '<label class="switch">			  <input type="checkbox" name="status" value="'.$res['id'].'">			  <span class="slider round"></span>			</label>';		}else if($res['status']==2){			$status = '<label class="switch">			  <input type="checkbox" name="status" value="'.$res['id'].'">			  <span class="slider round"></span>			</label>';		}else{ 			$status = '<label class="switch">			  <input type="checkbox" name="status" checked value="'.$res['id'].'">			  <span class="slider round"></span>			</label>';		}										if($res['user_type']==2){			$var="seller";		}else{			$var="customer";		}		echo "<tr>			<td>{$i}</td>			<td>{$res['name_online_store']}</td>			<td>{$res['email']}</td>			<td>{$res['mobile']}</td>			<td>{$res['gstin']}</td>			<td>$status</td>			<td>".(!empty($res['store_logo']) ? "<img src='{$imageurl}{$res['store_logo']}' style= 'max-height: 70px;'  alt=''/>" : "")."</td>			<!--<td><a href='seller_update?id={$res['id']}'class='btn'><i class='fas fa-edit'></i>edit</td></td>-->			<td><a href='user_view?id={$res['id']}'class='btn'><i class='fas fa-eye'></i>View</td></td>			<td><a href='javascript:void(0)' data-id='{$res['id']}'class='btn delete_vendor'><i class='fas fa-edit'></i>delete</a></td>		</tr>";	}}
echo '</tbody>';

echo "</table>";


?>
</section>
</div>
